#### **Assignment 3: Regularization and Distances**

**Members: Cui(Cathy) Yu, Shravani Mahadeshwar, Priya Botsa, Marc Hayes, Shaonan Feng and Di Yang**

- *Course: Machine Learning 2*
- *Prof: Jan Nagler*
- *Due: 25 April 2026*

#### **1. Regularization Study**

**Importing necessary libraries**

**Loading the dataset**

**EDA**

**Pre-processing**

**Ridge**

**Lasso**

**Elastic Net**

**Cross validation**

**Conclusion**

#### **2. Distances and Clustering in DNA-Like Sequences**

**Importing necessary libraries**

In [1]:
import pandas as pd
import numpy as np
from itertools import product
from scipy.spatial.distance import hamming, squareform
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.cluster import KMeans, DBSCAN, SpectralClustering      
import hdbscan                                       
from sklearn.manifold import MDS, TSNE
import umap
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
np.random.seed(42)

**Loading the dataset**

In [2]:
data=pd.read_csv("./data/highly_classified_data.csv",sep=";")
data.head()

     ID                                           Sequence  Unnamed: 2
0  seq1  CAAACTTATTCGACGATTGACTTAATCTTAATGATATCGAAGGTTA...         NaN
1  seq2  CAAACTTATTAGACGATTGACTTAATCTTAGTGATATCGAAGGTAA...         NaN
2  seq3  CAAACTTATTCGACGATTGACTTAATCTTAGTGATATCGAAGGTAA...         NaN
3  seq4  CAAACTTATTCGACGATTGACTTAATCTTAGTGATATCGAAGGTAA...         NaN
4  seq5  CAAACTTATTCGACGATTGACTTAATCTTAGTGATATCGAAGGTAA...         NaN

In [3]:
print(data['Unnamed: 2'].value_counts())
# Dropping the 'Unnamed: 2' column as it contains NaN 
data = data.drop(columns=['Unnamed: 2'])
data.sample(10)

Series([], Name: count, dtype: int64)

       ID                                           Sequence
83  seq84  GGAGGATTGAGGTTCAGTATCACCAAGTGCCTGACCAGGTGGTTAA...
53  seq54  ATAGGAGGTTTCGCGAAGTGGGTGATAGCCGATGGTAGCCGGCCCA...
70  seq71  ATAGGAGGTTTCGCGGAGTGGGTGATATCAGATTGTAGCCGGCCCA...
45  seq46  TTGCCGGACGTTCCCAGAGCTCCGGATGTGAACTTCGTTCACTGAT...
44  seq45  TTGCCGGACGTTCCCAGACCTCCGAATGTGAACTTCGTTCACTTCT...
39  seq40  TTGCCGGACGTTCCCAGACCTCCGAATGTGAACTTCGTTCACTTCT...
22  seq23  CAAACTTATTCGACGATTGACTTAATCTTAGTGATATCGAAGGTAA...
80  seq81  GGAGGCTTGAGGTGCAGTATCCCCCAGTGCTTGACCGGGTGCTTTA...
10  seq11  CAAACTTATTCGACGATTGACTTAATCTTAGTGATATCGAAGGTAA...
0    seq1  CAAACTTATTCGACGATTGACTTAATCTTAATGATATCGAAGGTTA...

**EDA**

**Sequence representation**

**Distance matrix**

**Clustering**

**Dimensionality reduction**

**Cluster validation**

**Within cluster sequence analysis**

**Metrics Conclusion**

**Conclusion**

**Take-away**

**1. Regularisation**

- 
- 



**2. Distances**

- 
-